name: bfsinkhorn
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - jax[cpu] >= 0.4.5
  - jaxlib
  - jaxopt
  - equinox
  - llvm-openmp
  - pyscf
  - pip
