name: bfsinkhorn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - compilers
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - jax
  - jaxlib>=0.3.7
  - pip
  - pip:
    - pyscf
