name: bfsinkhorn
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - jax[cpu]
  - jaxlib>=0.3.7
  - jaxopt
  - equinox
  - llvm-openmp
  - pyscf
  - pip
