name: Install package using mamba and run tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: 'bash -l {0}'

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python and install dependencies
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        create-args: python=${{ matrix.python-version }}
        cache-downloads: true
        cache-environment: true
    - name: Install bfsinkhorn
      run: pip install .[dev]
    - name: Test with pytest
      run: pytest
