name: Check styles using pre-commit

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: 'bash -l {0}'

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3


    - name: Set up Python and install dependencies
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yml
        extra-specs: |
          python=${{ matrix.python-version }}
        cache-downloads: true
        cache-env: true

    - name: Install pre-commit
      run: pip install pre-commit
    - name: Install pre-commit hooks
      run: pre-commit install
    - name: Run pre-commit
      run: pre-commit run --all-files
